name: PVPToggle
main: uk.co.ElmHoe.Main
version: 1.0
author: ElmHoe
load: POSTWORLD
commands:
   pvptoggle:
      description: The ability to be able to disable / enable PvP.
      aliases: [pvp]
      usage: /<command> [args]